// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateTodoInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type Mutation struct {
}

type Query struct {
}

type SignInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignUpInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UpdateTodoInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}
